
//----------------------------------------------------
// The following code was generated by CUP v0.10f
// Sat Apr 23 21:57:51 CDT 2016
//----------------------------------------------------

/** Cup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int STRLIT = 4;
  static final int rw_WHILE = 26;
  static final int rw_BOOL = 18;
  static final int LBRACKET = 21;
  static final int INCREMENT = 45;
  static final int rw_IF = 16;
  static final int SLASH = 35;
  static final int rw_CONTINUE = 42;
  static final int rw_FALSE = 34;
  static final int LPAREN = 7;
  static final int SEMI = 6;
  static final int rw_PRINT = 44;
  static final int rw_TRUE = 38;
  static final int DECREMENT = 46;
  static final int MINUS = 13;
  static final int RPAREN = 8;
  static final int NOT = 40;
  static final int INTLIT = 3;
  static final int rw_VOID = 30;
  static final int LT = 25;
  static final int rw_CONST = 24;
  static final int COMMA = 32;
  static final int rw_ELSE = 36;
  static final int GEQ = 33;
  static final int PLUS = 12;
  static final int rw_READ = 29;
  static final int rw_INT = 17;
  static final int EOF = 0;
  static final int RBRACKET = 39;
  static final int error = 1;
  static final int COR = 20;
  static final int rw_CLASS = 19;
  static final int rw_RETURN = 28;
  static final int EQ = 14;
  static final int ASG = 9;
  static final int TIMES = 31;
  static final int CHARLIT = 5;
  static final int COLON = 43;
  static final int LBRACE = 10;
  static final int rw_CHAR = 27;
  static final int RBRACE = 11;
  static final int CAND = 23;
  static final int LEQ = 37;
  static final int rw_BREAK = 41;
  static final int GT = 22;
  static final int NOTEQ = 15;
  static final int IDENTIFIER = 2;
}

